- Data/Constants.lua
- Data/Defaults.lua
- Menu/Builder.lua
- Util/Utils.lua
- WidgetAnnotations.lua
- Widgets/Bars/CastBar.lua
- Widgets/Texts/NameText.lua
> Cast bar text width option

- Annotations.lua
- Data/DBUtil.lua
- Locales/enUS.lua
- Menu/GeneralTab.lua
- Menu/Menu.lua
- Menu/UnitFramesTab.lua
- UnitFrames/MenuOptions.lua
Implements the option to copy widget settings from other units.
> [Feature] Copy widget settings from other units

- Locales/enUS.lua
- Menu/Menu.lua
- Menu/UnitFramesTab.lua
Change behaviour to always edit selected Master Layout instead of following what is selected in Cell.
> [Feature] Always edit selected Master Layout

- Data/Defaults.lua
- Locales/enUS.lua
- Menu/ColorTab.lua
- Widgets/Bars/ShieldBar.lua
Implements #55
Adds Texture and Color option in Color tab
> [Feature] Shield Bar texture option

- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- WidgetAnnotations.lua
- Widgets/Bars/ShieldBar.lua
> [Feature] Add option to anchor Shield Bar to Health Bar

- Data/Defaults.lua
- Locales/enUS.lua
- Menu/ColorTab.lua
- Util/Utils.lua
> [Feature] Pet Frame Class Color

- Data/Defaults.lua
- UnitFrames/MenuOptions.lua
- UnitFrames/UnitButton.lua
> [Feature] Health Bar Orientation Option

- API/Common.lua
- API/CustomAnchors.lua
- Cell_UnitFrames.toc
- Core/Init.lua
- UnitFrames/OnLoad.lua
- UnitFrames/UnitButton.lua
> [Feature] Add API for custom Positioning & Sizing of Unit Frames

- Locales/enUS.lua
- UnitFrames/EditMode.lua
Implements #61
Implements the ability to set abs positioning for various Cell Frames.
> [Feature] Add Cell Frames to Edit Mode

- Cell_UnitFrames.toc
- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- UnitFrames/OnLoad.lua
- WidgetAnnotations.lua
- Widgets/Auras/Auras.lua
- Widgets/Auras/Dispels.lua
Implements #90
Implements Dispels widget.
Adds the option to highlight the frame and/or display a corresponding dispel icon.
> [Feature] Implement Dispels Widget

- Data/Defaults.lua
- Locales/enUS.lua
- UnitFrames/MenuOptions.lua
- Widgets/Bars/PowerBar.lua
Implements #120
Implements a toggle for using Cells `Power Bar Filters` for each Unit.
> [Feature] Add Power Filter toggle

- Data/Constants.lua
- Data/Defaults.lua
- Data/Revise.lua
- Menu/Builder.lua
- UnitFrames/MenuOptions.lua
- UnitFrames/UnitButton.lua
- WidgetAnnotations.lua
- Widgets/Auras/Auras.lua
> [Feature] Add horizontal growth for Boss Frames

- Data/Defaults.lua
- Locales/enUS.lua
- UnitFrames/MenuOptions.lua
- UnitFrames/OnLoad.lua
- UnitFrames/UnitButton.lua
Should resolve #146
Implements an "Always Update" toggle for TargetTarget frame.
When enabled the frame will full update on the OnTick cycle.
> [Feature] Add "Always Update" toogle for TargetTarget frames

- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- WidgetAnnotations.lua
- Widgets/Bars/CastBar.lua
> [Feature] Add "Only show interruptable casts" toggle for Cast Bar

- Cell_UnitFrames.toc
- Core/Init.lua
- Core/OnLoad.lua
- Core/SlashCommands.lua
- Data/DBUtil.lua
- Data/Database.lua
- Locales/enUS.lua
- Menu/GeneralTab.lua
- Menu/Menu.lua
- UnitFrames/EditMode.lua
- UnitFrames/OnLoad.lua
- UnitFrames/UnitButton.lua
- Util/PixelPerfect.lua
- Util/Utils.lua
- Widgets/Auras/Auras.lua
- Widgets/Auras/Totems.lua
- Widgets/Auras/Updater.lua
- Widgets/Bars/CastBar.lua
- Widgets/Bars/ClassBar.lua
- Widgets/Bars/HealAbsorb.lua
- Widgets/Bars/HealthBar.lua
- Widgets/Bars/PowerBar.lua
- Widgets/Bars/ShieldBar.lua
- Widgets/Common.lua
- Widgets/Texts/BaseTextWidget.lua
Properly implements the ability to scale the UI elements.
> [Feature] Implement proper Scaling support

- Core/OnLoad.lua
- Data/Constants.lua
- Data/DBUtil.lua
- Data/Defaults.lua
- Data/Revise.lua
- Locales/enUS.lua
- Menu/GeneralTab.lua
- UnitFrames/MenuOptions.lua
- UnitFrames/UnitButton.lua
- Util/HideBlizzard.lua
Implements #135
Implements the option to selectively hide blizzard frames independently of unit frame settings.
> [Feature] Add options for selectively hiding default blizzard frames

- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- Util/Utils.lua
- WidgetAnnotations.lua
- Widgets/Auras/Auras.lua
- Widgets/Auras/Updater.lua
Implements #139
Adds a toggle for showing Temporary Enchants.
> [Feature] Add toggle for showing Temporary Enchants 

- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- WidgetAnnotations.lua
- Widgets/Auras/Dispels.lua
Implements #136
Implements Glow options for widget menu,
Implements option to add Glow for Dispels.
> [Feature] Dispel Border Glow

- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- WidgetAnnotations.lua
- Widgets/Bars/CastBar.lua
> [Feature] Unitname on Cast Bar

- Cell_UnitFrames.toc
- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- Menu/ColorTab.lua
- WidgetAnnotations.lua
- Widgets/Misc/Highlight.lua
Implements #142
Implements new widget for Highligting current target and frames hovered over.
> [Feature] Frame Highlighting

- Data/DBUtil.lua
- Data/Revise.lua
- Menu/AuraFilterList.lua
- Menu/Builder.lua
- Menu/ColorTab.lua
- Menu/GeneralTab.lua
- UnitFrames/MenuOptions.lua
- UnitFrames/OnLoad.lua
- UnitFrames/UnitButton.lua
- Util/Utils.lua
- Widgets/Auras/Auras.lua
- Widgets/Auras/Dispels.lua
- Widgets/Bars/HealthBar.lua
- Widgets/Common.lua
- Widgets/Misc/Highlight.lua
- Widgets/Texts/CustomFormats.lua
- Widgets/Texts/CustomText.lua
https://github.com/Ghostopheles/wow-ui-source/blob/live/Interface/AddOns/Blizzard_SharedXMLBase/Compat.lua
> [Misc] Lua 4 compat cleanup

- Cell_UnitFrames.toc
- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- WidgetAnnotations.lua
- Widgets/Bars/AltPowerBar.lua
> [Feature] Alt Power Bar widget

- .gitignore
- .pkgmeta
- Annotations.lua
- Cell_UnitFrames.toc
- Core/OnLoad.lua
- Data/Constants.lua
- Data/Defaults.lua
- Locales/enUS.lua
- Menu/Builder.lua
- UnitFrames/AurasMixin.lua
- WidgetAnnotations.lua
- Widgets/Auras/Dispels.lua
> [Feature] Show Soothe/Purge dispels for hostile units

- Data/Defaults.lua
- Locales/enUS.lua
- Menu/AppearanceTab.lua
- UnitFrames/UnitButton.lua
- Widgets/Bars/HealAbsorb.lua
- Widgets/Bars/HealPrediction.lua
- Widgets/Bars/ShieldBar.lua
> [Misc] Add "Reverse Health Fill" toggle
